remove obsolete flag from manifests
This flag was obsoleted as per kubernetes/kubernetes#51376 and will
trigger an exception on `fluentd` container:

```sh
2019-07-23 17:29:29 +0000 [error]: unexpected error error_class=NoMethodError error="undefined method `[]' for nil:NilClass"
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:335:in `detect_es_major_version'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:245:in `block in configure'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.5.2/lib/fluent/plugin/out_elasticsearch.rb:244:in `configure'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/plugin.rb:164:in `configure'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/agent.rb:130:in `add_match'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/agent.rb:72:in `block in configure'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/agent.rb:64:in `each'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/agent.rb:64:in `configure'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/root_agent.rb:150:in `configure'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/engine.rb:131:in `configure'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/engine.rb:96:in `run_configure'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/supervisor.rb:801:in `run_configure'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/supervisor.rb:548:in `block in run_worker'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/supervisor.rb:730:in `main_process'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/supervisor.rb:544:in `run_worker'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/lib/fluent/command/fluentd.rb:316:in `<top (required)>'
  2019-07-23 17:29:29 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-07-23 17:29:29 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-07-23 17:29:29 +0000 [error]: /var/lib/gems/2.3.0/gems/fluentd-1.5.1/bin/fluentd:8:in `<top (required)>'
  2019-07-23 17:29:29 +0000 [error]: /usr/local/bin/fluentd:22:in `load'
  2019-07-23 17:29:29 +0000 [error]: /usr/local/bin/fluentd:22:in `<main>'
```

Resolves: kubernetes/kubernetes#51376
Related: fluent/fluentd-kubernetes-daemonset#335
Signed-off-by: Daniel Andrei Minca <mandrei17@gmail.com>